version: '3.4'
services:
  sodexoayuda.web:
    image: ${DOCKER_REGISTRY-}sodexoayudaweb
    ports:
      - 20002:8000
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '1.00'
          memory: 1024M
    restart: always
    environment:
        PORT: 8000
        PUBLIC_URL: /
        REACT_APP_VERSION: $npm_package_version
        REACT_APP_KEY: SDX-123
        NODE_OPTIONS: --max_old_space_size=1024

        REACT_APP_BASE_URL: http://host.docker.internal:20001/api
